version: '3.3'

services:
  tech-challenge:
    container_name: tech-challenge
    build:
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql-docker
    restart: "no"
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: tech_challenge
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - backend
    volumes:
    - ./data:/var/lib/mysql

networks:
  backend: